notifications:
  email: false

language: node_js
node_js: node

deploy:
  - provider: script
    skip_cleanup: true
    script: bash .travis/pu.sh $TRAVIS_TAG
    on:
      tags: true
      branch: master
  - provider: npm
    email: chris@cgames.nl
    skip_cleanup: true
    api_key:
      secure: "VI4JiCbqHZioSSMdHbpB+Dz/AGpe4APZWK9zzK4ryjZvYfuNMtgQ0GZI57pBfd1n726pJiXrdb0ShqYqoB3KTVPsMkpLWFNU/nn09FuAGSRroQrFEZY9M2GjXGPdb8lMXtNm32/8oASHIabLlWlF+TuARMeSIBOfwb5xtK1n9yPIsBDIyJrWOnBlV9Q9xWzdGh9zDbf8TtVhUuISWDHMZX5UuTCe8MwbEgdTG7x+d6Je4qktowKSjyM5gb1kAOzDk+7ZG86RpdWdHOAMnwEm6dzSMYHFbC0wBPoU+pKUhQQjmOjtulsUU5PArwoSTbqy+19NlLvh9rMDBPZUVBWfiOc8tissuZCN3CowSED0FhuTpewb+GDTeD8gCw2IviRNHW4L3icXU4lyFom5vopST2tuRymBPg7ZGO0phgLpOK7UxY9+dCAXsk38nrP8baU6+QDjuSEAETkiOJiERsRlvQFkc7vWe81PLzAERj64hHMBBe0gjD0RVY5OBdUSvQK41wlosdMn+zxXfOAyNIXs9C9bhx1xRlCR841hnDXAs3aI7/KzZEF3c4yYqUis9NHDzNCmp7kxuGIuIwSCLiUU6EpvHCksgOuUN25nshL0wyqhHhir+wwjQ8i4DqJCq7k2uxG36b4r3iP8qnns+U3gXw/NobBBlYdZahkQuFVgZ20="
    on:
      tags: true
      branch: master
